# Generated by Django 6.1.1 on 2026-09-23 05:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("user_profiles", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserActivity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("track_id", models.CharField(max_length=200)),
                ("track_name", models.CharField(blank=True, max_length=300)),
                ("artist_name", models.CharField(blank=True, max_length=300)),
                ("genre", models.CharField(blank=True, max_length=100)),
                (
                    "action",
                    models.CharField(
                        choices=[("play", "Play"), ("like", "Like"), ("skip", "Skip")],
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activities",
                        to="user_profiles.userprofile",
                    ),
                ),
            ],
        ),
    ]
